# Generated by Django 2.0.4 on 2018-05-28 07:38

import crud_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('post_text', crud_project.models.NormalTextField(default='Message Deleted')),
            ],
            options={
                'ordering': ('date_posted',),
            },
        ),
    ]
